name: Test

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  RSpec:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - alchemy_cms: "7.4"
            rails: "7.2"
            ruby: "3.3"
          - alchemy_cms: "7.4"
            rails: "8.0"
            ruby: "3.4"
          - alchemy_cms: "8.0"
            rails: "8.0"
            ruby: "3.4"
    env:
      RAILS_VERSION: ${{ matrix.rails }}
      ALCHEMY_CMS_VERSION: ${{ matrix.alchemy_cms }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
          rubygems: "latest"

      - name: Prepare database
        run: bundle exec rake spec:db_prepare

      - name: Run tests
        run: bundle exec rspec

      - uses: actions/upload-artifact@main
        if: failure()
        with:
          name: Screenshots
          path: spec/dummy/tmp/capybara
